### ISSUE TITLE
Multi word search with the new corpus

### ISSUE THREAD

**Issue by erikao1998** [erikao1998/crispy-rotary-phone#18]
The code in general works pretty well with the movie subtitles but certain features, like the multi word search, don't. I tried for a while to make it work but finally gave up and commented almost half of the search() function.

**Comment by suvis705** [comment]
The search function doesn't work at all when I tested the program. I tried to go through the code line by line combining some stuff from @erikao1998 branch and the main one, but it seems we would need to specify the variable "number" to be global instead of local. I just don't know where in the code this needs to happen.

**Comment by panukap** [comment]
Is there any way to know what words exist in the files the user wants to look at before getting to here?
```
for x in range(len(genres)):
                            doc, names = open_file(genres[x], all_years[x])
                            articles = search_article(words, number, doc, names)
                            all_articles[genres[x]] = articles
```
Everything else seems to work for me now (I think the original problem was because of some code that was copied wrong) except that the variable _subtitles_ doesn't exist yet, and it seems like it can exist only after opening the files. However, the errors and checking of which words don't exist in the chosen genres (so the function knows not to take them into account but still give results for the rest of the words) happens before opening the files. Should I put my version of the otherwise now (I think) working code to the main branch?

**Comment by panukap** [comment]
This should work: ` #if the user has entered something in both fields
    if number and words:
        for x in range(len(genres)):
            doc, names = open_file(genres[x], all_years[x])
        try:
            number = int(number)# converts the number into an integer
        except:
            number = 0
        if number <= 0:
            errors = ["Invalid input. Please enter an integer larger than 0."]
        else:
            for w in words.split(): # separates input into words
                # if a word (letters separated by non-letters) is not in the documents, informs user of the unknown word(s)
                if w not in set(re.split("\W", (" ".join(subs.lower() for d in doc for subs in d.split())))) or w[-2:] == "'s":
                    errors.append("") # add dummy item to errors list for the html to know to still show articles
                    if w[-2:] == "'s": # if user searches for word with possessive suffix, show appropriate message
                        errors.append("Write possessive suffixes as separate words without an apostrophe.")
                    else: # otherwise tells user which word(s) is/are unknown
                        errors.append("\"{:s}\" is an unknown word.".format(w))
                    words = " ".join([word for word in words.split() if word != w]) # deletes unknown words from input
                    number -= 1 # decreases the user's number according to the number of unknown words
            if len(words) > 0:
                if number <= 0 and len(words.split()) > 0:
                    number = len(words.split())
                try:
                    if len(genres) == 0:
                        errors = ["Select at least one genre"]
                    if len(all_years) < len(genres):
                        errors = ["Select at least one year for the selected genres"]
                    else:
                        for x in range(len(genres)):
                            articles = search_article(words, number, doc, names)
                            all_articles[genres[x]] = articles

                except IndexError:
                    errors = ["No matching documents found."]
    else:
        errors = ["Enter both a number and at least one word."]`

**Comment by panukap** [comment]
_EDIT:_ Found an issue with it showing all results together, once for each genre. This should work correctly now:  
```
#if the user has entered something in both fields
    if number and words:
        for x in range(len(genres)):
            all_docs, all_names = open_file(genres[x], all_years[x])
        try:
            number = int(number)# converts the number into an integer
        except:
            number = 0
        if number <= 0:
            errors = ["Invalid input. Please enter an integer larger than 0."]
        else:
            for w in words.split(): # separates input into words
                # if a word (letters separated by non-letters) is not in the documents, informs user of the unknown word(s)
                if w not in set(re.split("\W", (" ".join(subs.lower() for d in all_docs for subs in d.split())))) or w[-2:] == "'s":
                    errors.append("") # add dummy item to errors list for the html to know to still show articles
                    if w[-2:] == "'s": # if user searches for word with possessive suffix, show appropriate message
                        errors.append("Write possessive suffixes as separate words without an apostrophe.")
                    else: # otherwise tells user which word(s) is/are unknown
                        errors.append("\"{:s}\" is an unknown word.".format(w))
                    words = " ".join([word for word in words.split() if word != w]) # deletes unknown words from input
                    number -= 1 # decreases the user's number according to the number of unknown words
            if len(words) > 0:
                if number <= 0 and len(words.split()) > 0:
                    number = len(words.split())
                try:
                    if len(genres) == 0:
                        errors = ["Select at least one genre"]
                    if len(all_years) < len(genres):
                        errors = ["Select at least one year for the selected genres"]
                    else:
                        for x in range(len(genres)):
                            doc, names = open_file(genres[x], all_years[x])
                            articles = search_article(words, number, doc, names)
                            all_articles[genres[x]] = articles

                except IndexError:
                    errors = ["No matching documents found."]
    else:
        errors = ["Enter both a number and at least one word."]
```

**Comment by suvis705** [comment]
@panukap Great job! Yeah, I think you should put your version to main so that we will at least have a functioning version there.

**Comment by panukap** [comment]
Added to main and merged with my other changes.
